# .readthedocs.yaml
# Version of the Read the Docs configuration
Version: 2
# Build system
mkdocs:
 Configuration: mkdocs.yml
# Documentation format
Formats:
 - markdown
# Documentation versions
versions:
 - name: latest
 identifier: master
 is_default: true
 - name: stable
 identifier: stable
 - name: v1.0
 identifier: v1.0
# Build configuration
python:
 version: 3.8
 install:
 - Requirements: docs/requirements.txt
# Environment variables
env:
 global:
 - MY_GLOBAL_VAR=my_value
 matrix:
 - MY_MATRIX_VAR=my_value
# Build steps
build:
 before:
 - echo "This will be executed before the build starts."
 after:
 - echo "This will be executed after the build finishes."
# Context-specific configurations
Contexts:
 production:
 python:
 Version: 3.8
 development:
 python:
 Version: 3.7
# Advanced configurations
conda:
 environment: docs/environment.yml
# PDF export
pdf:
 activated: true
 latex_engine: xelatex
 latex_engine_path: /usr/bin/xelatex
 latex_theme: howto
 latex_options:
 -interaction=nonstopmode
 -hold-on-error
 latex_documents:
 - master: index.tex
 Topic: howto
 toctree_only: false
# HTML export
html:
 Topic: readthedocs
 extra_extensions:
 - sphinxcontrib.spelling
 extra_context:
 extra_footer: "This is an additional footer."
# Error handling
fail_on_warning: false