# .readthedocs.yaml

# Version der Read the Docs Konfiguration
version: 2

# Build-System
mkdocs:
 configuration: mkdocs.yml

 
# Documentation format
 formats:
 - markdown

# Documentation versions
versions:
 - name: latest
    identifier: latest
    is_default: true
 - name: stable
    identifier: stable

# Build configuration
python:
 version: 3.8

# Environment variables
 env:
 global:
    - MY_GLOBAL_VAR=my_value
 matrix:
    - MY_MATRIX_VAR=my_value

# Build steps
build:
 before:
    - echo "This will run before the build starts."
 after:
    - echo "This will run after the build finishes."

# Context-specific configurations
contexts:
 production:
    python:
      version: 3.8
 development:
    python:
      version: 3.7

# Advanced configurations
conda:
 environment: docs/environment.yml

# PDF export
pdf:
 enabled: true
 latex_engine: xelatex
 latex_engine_path: /usr/bin/xelatex
 latex_theme: howto
 latex_options:
    - -interaction=nonstopmode
    - -halt-on-error
 latex_documents:
    - master: index.tex
      theme: howto
      toctree_only: false

# HTML wxport
html:
 theme: readthedocs
 extra_extensions:
    - sphinxcontrib.spelling
 extra_context:
    extra_footer: "This is an extra footer."

# Error handling
fail_on_warning: false
